# Generated by Django 4.1.2 on 2022-10-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativeQuestions',
            fields=[
                ('idquestions_alternatives', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('letter', models.CharField(blank=True, max_length=1, null=True)),
                ('certain', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'alternative_questions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('idcase', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'cases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('idquestionnaire', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('Subject', models.CharField(blank=True, max_length=250, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('quests', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'questionnaire',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('idquestions', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.IntegerField(blank=True, db_column='questaoNum', null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'questions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionTypes',
            fields=[
                ('idtype_questions', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'question_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('idresult', models.AutoField(primary_key=True, serialize=False)),
                ('descriptiondate', models.DateTimeField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'result',
                'managed': False,
            },
        ),
    ]
