# Generated by Django 4.1.2 on 2022-10-24 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternativequestions',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cases',
            options={},
        ),
        migrations.AlterModelOptions(
            name='questionnaire',
            options={},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={},
        ),
        migrations.AlterModelOptions(
            name='questiontypes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={},
        ),
    ]
