# Generated by Django 4.1.2 on 2022-12-02 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_initial'),
        ('video', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='codimage',
            field=models.ForeignKey(blank=True, db_column='codimagem', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='images.image', verbose_name='Link Image'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='questionnaireidquestionnaire',
            field=models.ForeignKey(blank=True, db_column='questionarioidquestionario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='questions.questionnaire', verbose_name='Related Subject'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='typequestionandidtypequestion',
            field=models.ForeignKey(blank=True, db_column='tipoquestoesidtipoquestoes', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='questions.questiontypes', verbose_name='Type of Question'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='videoidvideo',
            field=models.ForeignKey(blank=True, db_column='videoidvideo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='video.video', verbose_name='Link Video'),
        ),
    ]
