# Generated by Django 4.1.2 on 2022-10-24 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_initial'),
        ('accounts', '0002_alter_user_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0001_initial'),
        ('questions', '0002_alter_alternativequestions_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativequestions',
            name='questoes_questoes_id',
            field=models.ForeignKey(blank=True, db_column='questoes_idquestoes', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='questions.questions'),
        ),
        migrations.AddField(
            model_name='cases',
            name='imageidimage',
            field=models.ForeignKey(blank=True, db_column='imagemidimagem', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='images.image'),
        ),
        migrations.AddField(
            model_name='cases',
            name='this_question',
            field=models.ForeignKey(blank=True, db_column='questoesidquestao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='questions.questions'),
        ),
        migrations.AddField(
            model_name='cases',
            name='useriduser',
            field=models.ForeignKey(blank=True, db_column='usuarioidusuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='co_educator',
            field=models.ForeignKey(blank=True, db_column='codidusuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='usercode',
            field=models.ForeignKey(blank=True, db_column='codtipousuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.usertype'),
        ),
        migrations.AddField(
            model_name='questions',
            name='codimage',
            field=models.ForeignKey(blank=True, db_column='codimagem', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='images.image'),
        ),
        migrations.AddField(
            model_name='questions',
            name='questionnaireidquestionnaire',
            field=models.ForeignKey(blank=True, db_column='questionarioidquestionario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='questions.questionnaire'),
        ),
        migrations.AddField(
            model_name='questions',
            name='typequestionandidtypequestion',
            field=models.ForeignKey(blank=True, db_column='tipoquestoesidtipoquestoes', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='questions.questiontypes'),
        ),
        migrations.AddField(
            model_name='questions',
            name='videoidvideo',
            field=models.ForeignKey(blank=True, db_column='videoidvideo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='video.video'),
        ),
        migrations.AddField(
            model_name='result',
            name='iduser_user',
            field=models.ForeignKey(blank=True, db_column='usuario_idusuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='result',
            name='quiz_quiz_id',
            field=models.ForeignKey(blank=True, db_column='questionario_idquestionario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='questions.questionnaire'),
        ),
    ]
