# Generated by Django 4.1.2 on 2022-10-24 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alternativequestions_questoes_questoes_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cases',
            name='imageidimage',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='this_question',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='useriduser',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='co_educator',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='usercode',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='codimage',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='questionnaireidquestionnaire',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='typequestionandidtypequestion',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='videoidvideo',
        ),
        migrations.RemoveField(
            model_name='result',
            name='iduser_user',
        ),
        migrations.RemoveField(
            model_name='result',
            name='quiz_quiz_id',
        ),
        migrations.DeleteModel(
            name='AlternativeQuestions',
        ),
        migrations.DeleteModel(
            name='Cases',
        ),
        migrations.DeleteModel(
            name='Questionnaire',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='QuestionTypes',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
