# Generated by Django 4.1.2 on 2022-10-24 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_alter_user_password'),
        ('video', '0005_initial'),
        ('questions', '0004_remove_cases_imageidimage_remove_cases_this_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('idquestionnaire', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('Subject', models.CharField(blank=True, max_length=250, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('quests', models.IntegerField(blank=True, null=True)),
                ('co_educator', models.ForeignKey(blank=True, db_column='codidusuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('usercode', models.ForeignKey(blank=True, db_column='codtipousuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.usertype')),
            ],
            options={
                'db_table': 'questionnaire',
            },
        ),
        migrations.CreateModel(
            name='QuestionTypes',
            fields=[
                ('idtype_questions', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'question_types',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('idresult', models.AutoField(primary_key=True, serialize=False)),
                ('descriptiondate', models.DateTimeField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('iduser_user', models.ForeignKey(blank=True, db_column='usuario_idusuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('quiz_quiz_id', models.ForeignKey(blank=True, db_column='questionario_idquestionario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='questions.questionnaire')),
            ],
            options={
                'db_table': 'result',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('idquestions', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.IntegerField(blank=True, db_column='questaoNum', null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('codimage', models.ForeignKey(blank=True, db_column='codimagem', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='images.image')),
                ('questionnaireidquestionnaire', models.ForeignKey(blank=True, db_column='questionarioidquestionario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='questions.questionnaire')),
                ('typequestionandidtypequestion', models.ForeignKey(blank=True, db_column='tipoquestoesidtipoquestoes', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='questions.questiontypes')),
                ('videoidvideo', models.ForeignKey(blank=True, db_column='videoidvideo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='video.video')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('idcase', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=250, null=True)),
                ('imageidimage', models.ForeignKey(blank=True, db_column='imagemidimagem', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='images.image')),
                ('this_question', models.ForeignKey(blank=True, db_column='questoesidquestao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='questions.questions')),
                ('useriduser', models.ForeignKey(blank=True, db_column='usuarioidusuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cases',
            },
        ),
        migrations.CreateModel(
            name='AlternativeQuestions',
            fields=[
                ('idquestions_alternatives', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('letter', models.CharField(blank=True, max_length=1, null=True)),
                ('certain', models.CharField(blank=True, max_length=1, null=True)),
                ('questoes_questoes_id', models.ForeignKey(blank=True, db_column='questoes_idquestoes', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='questions.questions')),
            ],
            options={
                'db_table': 'alternative_questions',
            },
        ),
    ]
