# Generated by Django 4.1.2 on 2022-10-24 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cases',
            name='imageidimage',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='codimage',
        ),
    ]
