# Generated by Django 4.1.2 on 2022-10-24 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_initial'),
        ('questions', '0006_remove_cases_imageidimage_remove_questions_codimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='imageidimage',
            field=models.ForeignKey(blank=True, db_column='imagemidimagem', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='images.image'),
        ),
        migrations.AddField(
            model_name='questions',
            name='codimage',
            field=models.ForeignKey(blank=True, db_column='codimagem', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='images.image'),
        ),
    ]
