# Generated by Django 4.1.2 on 2022-10-24 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0007_initial'),
        ('demarcate', '0002_delete_demarcate'),
    ]

    operations = [
        migrations.CreateModel(
            name='demarcate',
            fields=[
                ('idmarks', models.AutoField(primary_key=True, serialize=False)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('w', models.IntegerField(blank=True, null=True)),
                ('h', models.IntegerField(blank=True, null=True)),
                ('right', models.IntegerField(blank=True, null=True)),
                ('bottom', models.IntegerField(blank=True, null=True)),
                ('area', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('idimage', models.ForeignKey(blank=True, db_column='idimagem', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='images.image')),
            ],
            options={
                'db_table': 'demarcate',
            },
        ),
    ]
