# Generated by Django 4.1.2 on 2022-10-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('idforum', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'forum',
                'managed': False,
            },
        ),
    ]
