# Generated by Django 4.1.2 on 2022-11-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_confirm_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirm_password',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='abc@123', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
