# Generated by Django 4.1.2 on 2022-10-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('idreport', models.AutoField(primary_key=True, serialize=False)),
                ('report', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'report',
                'managed': False,
            },
        ),
    ]
