# Generated by Django 4.1.2 on 2022-10-24 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='idimage',
        ),
    ]
