# Generated by Django 4.1.2 on 2022-10-24 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_remove_cases_imageidimage_remove_questions_codimage'),
        ('reports', '0006_remove_report_idimage'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='ImagesQuestions',
        ),
        migrations.DeleteModel(
            name='ImageType',
        ),
        migrations.DeleteModel(
            name='Specialty',
        ),
    ]
