# Generated by Django 4.1.2 on 2022-10-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0004_delete_image_delete_imagesquestions_delete_imagetype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('idimage', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(blank=True, max_length=250, null=True)),
                ('dataimg', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImagesQuestions',
            fields=[
                ('idimages_questions', models.AutoField(primary_key=True, serialize=False)),
                ('daterecord', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'images_questions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImageType',
            fields=[
                ('id_type_image', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'image_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('idespecialty', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'specialty',
                'managed': False,
            },
        ),
    ]
