# Generated by Django 4.1.2 on 2022-10-24 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='ImagesQuestions',
        ),
        migrations.DeleteModel(
            name='ImageType',
        ),
        migrations.DeleteModel(
            name='Specialty',
        ),
    ]
