# Generated by Django 4.1.2 on 2022-10-24 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0006_remove_cases_imageidimage_remove_questions_codimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0006_delete_image_delete_imagesquestions_delete_imagetype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('idimage', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(blank=True, max_length=250, null=True)),
                ('dataimg', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='ImageType',
            fields=[
                ('id_type_image', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'image_type',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('idespecialty', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'specialty',
            },
        ),
        migrations.CreateModel(
            name='ImagesQuestions',
            fields=[
                ('idimages_questions', models.AutoField(primary_key=True, serialize=False)),
                ('daterecord', models.DateTimeField(blank=True, null=True)),
                ('id_image', models.ForeignKey(blank=True, db_column='id_imagem', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='images.image')),
                ('id_quest', models.ForeignKey(blank=True, db_column='id_questao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='questions.questions')),
            ],
            options={
                'db_table': 'images_questions',
            },
        ),
        migrations.AddField(
            model_name='image',
            name='codtype_picture',
            field=models.ForeignKey(blank=True, db_column='codtipoimagem', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='images.imagetype'),
        ),
        migrations.AddField(
            model_name='image',
            name='specialtydespecialty',
            field=models.ForeignKey(blank=True, db_column='especialidadeidespecialidade', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='images.specialty'),
        ),
        migrations.AddField(
            model_name='image',
            name='useriduser',
            field=models.ForeignKey(blank=True, db_column='usuarioidusuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
