# Generated by Django 4.1.2 on 2022-10-24 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={},
        ),
    ]
