# Generated by Django 4.1.2 on 2022-10-24 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_video_co_educator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
